### ISSUE TITLE
Is it possible to have multiple crates drop at the same time?

### ISSUE THREAD

**Issue by simonk83** [WheteThunger/BetterChinookPath#2]
Rather than drop one and move to another monument to drop another, is there a way to have it just drop two?

**Comment by WheteThunger** [comment]
My goals with this plugin was primarily to fix the vanilla patrol RNG, and to allow chinooks to visit a configurable list of monuments. The feature to drop multiple crates was only added because it was super convenient to do so (the plugin just updates the `numCrates` property of the chinook), and because it's slightly in scope for the plugin since it affects the chinook's patrol behavior (it continues patrolling rather than leaving if it has more crates). I'm hesitant to add more scope, lest this plugin become a complete chinook overhaul, which I don't have time to take on anytime soon.

Based on a quick perusal of the Rust code, if I were to add this feature, I think I would utilize the `OnHelicopterDropCrate` hook to detect when a crate was dropped, then get the associated chinook component, then update the `nextDropTime` on the next frame. I would also add a config option to determine the maximum number of crates that can be dropped in short succession, and track state in the chinook component to make sure that limit is respected. Would you like to take a crack at adding this feature and make a PR?

**Comment by simonk83** [comment]
Yep totally understand it's not really a crate modification plugin, I just happened to start messing with it and wasn't sure if it was possible, but yep I might have a crack!
